### ISSUE TITLE
Reproduce experiments

### ISSUE THREAD

**Issue by goodbai-nlp** [xuewyang/LaSyn#1]
Hi, 

Thanks for your great work! When I tried to reproduce your experiments, I got the following problem:

    Traceback (most recent call last):
      File "/nfs/Desktop/MT/Syn-MT/fairseq_cli/train.py", line 422, in <module>
        cli_main()
      File "/nfs/Desktop/MT/Syn-MT/fairseq_cli/train.py", line 418, in cli_main
        main(args)
      File "/nfs/Desktop/MT/Syn-MT/fairseq_cli/train.py", line 93, in main
        trainer.dummy_train_step([dummy_batch])
      File "/nfs/Desktop/MT/Syn-MT/fairseq/trainer.py", line 364, in dummy_train_step
        self.train_step(dummy_batch, dummy_batch=True)
      File "/nfs/Desktop/MT/Syn-MT/fairseq/trainer.py", line 215, in train_step
        raise e
      File "/nfs/Desktop/MT/Syn-MT/fairseq/trainer.py", line 203, in train_step
        ignore_grad
      File "/nfs/Desktop/MT/Syn-MT/fairseq/tasks/fairseq_task.py", line 280, in train_step
        loss, sample_size, logging_output = criterion(model, sample)
      File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
        result = self.forward(*input, **kwargs)
      File "/nfs/Desktop/MT/Syn-MT/fairseq/criterions/label_smoothed_cross_entropy.py", line 317, in forward
        loss1, nll_loss, loss_c, nll_loss_c = self.compute_loss(net_output, sample, reduce=reduce)
      File "/nfs/Desktop/MT/Syn-MT/fairseq/criterions/label_smoothed_cross_entropy.py", line 343, in compute_loss
        gamma = self.e_step(Pz_x, Py_zx)
      File "/nfs/Desktop/MT/Syn-MT/fairseq/criterions/label_smoothed_cross_entropy.py", line 381, in e_step
        gamma = Pz_x * Py_zx  # responsibility      # B, S, 40
    RuntimeError: The size of tensor a (32) must match the size of tensor b (40) at non-singleton dimension 1
Do you have any idea about how to solve it?

**Comment by xuewyang** [comment]
Hi, 

Thank you for your interest. I think 40 is the size of the vocabulary of POS tags. Can you verify that your vocabulary size is 40?
